load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "specs_lib",
    srcs = ["main.go"],
    importpath = "github.com/retail-cortex/blitz/tools/specs",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "specs",
    embed = [":specs_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "specs_test",
    srcs = ["main_test.go"],
    embed = [":specs_lib"],
)
