// Icons for files by their name.
import {
  mdiCodeJson,
  mdiConsole,
  mdiDatabaseOutline,
  mdiDocker,
  mdiFileCogOutline,
  mdiFileDocumentOutline,
  mdiFileImageOutline,
  mdiFileOutline,
  mdiLanguageC,
  mdiLanguageCpp,
  mdiLanguageCss3,
  mdiLanguageGo,
  mdiLanguageHtml5,
  mdiLanguageJava,
  mdiLanguageJavascript,
  mdiLanguageKotlin,
  mdiLanguageMarkdownOutline,
  mdiLanguagePhp,
  mdiLanguagePython,
  mdiLanguageRuby,
  mdiLanguageRust,
  mdiLanguageSwift,
  mdiLanguageTypescript,
} from "@mdi/js";

const byExtension: Record<string, string> = {
  go: mdiLanguageGo,
  ts: mdiLanguageTypescript,
  tsx: mdiLanguageTypescript,
  js: mdiLanguageJavascript,
  jsx: mdiLanguageJavascript,
  mjs: mdiLanguageJavascript,
  cjs: mdiLanguageJavascript,
  py: mdiLanguagePython,
  rs: mdiLanguageRust,
  java: mdiLanguageJava,
  kt: mdiLanguageKotlin,
  swift: mdiLanguageSwift,
  rb: mdiLanguageRuby,
  php: mdiLanguagePhp,
  c: mdiLanguageC,
  h: mdiLanguageC,
  cc: mdiLanguageCpp,
  cpp: mdiLanguageCpp,
  hpp: mdiLanguageCpp,
  html: mdiLanguageHtml5,
  css: mdiLanguageCss3,
  scss: mdiLanguageCss3,
  md: mdiLanguageMarkdownOutline,
  json: mdiCodeJson,
  yaml: mdiFileCogOutline,
  yml: mdiFileCogOutline,
  toml: mdiFileCogOutline,
  bazel: mdiFileCogOutline,
  bzl: mdiFileCogOutline,
  mod: mdiFileCogOutline,
  sh: mdiConsole,
  bash: mdiConsole,
  zsh: mdiConsole,
  sql: mdiDatabaseOutline,
  png: mdiFileImageOutline,
  jpg: mdiFileImageOutline,
  jpeg: mdiFileImageOutline,
  gif: mdiFileImageOutline,
  svg: mdiFileImageOutline,
  webp: mdiFileImageOutline,
  txt: mdiFileDocumentOutline,
};

export function fileIcon(name: string): string {
  if (/^dockerfile/i.test(name)) return mdiDocker;
  if (/^(makefile|build|workspace|module)(\.bazel)?$/i.test(name)) return mdiFileCogOutline;
  const ext = name.includes(".") ? name.slice(name.lastIndexOf(".") + 1).toLowerCase() : "";
  return byExtension[ext] ?? mdiFileOutline;
}
