// Copyright 2026 Retail Cortex
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package search

import (
	"context"
	"errors"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fakeEnricher describes a file by its title, and counts its calls.
type fakeEnricher struct {
	mu     sync.Mutex
	titles []string
	fail   error
}

func (f *fakeEnricher) Describe(_ context.Context, title, text string) (Description, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.fail != nil {
		return Description{}, f.fail
	}
	f.titles = append(f.titles, title)
	d := Description{Summary: "About " + title + ": " + strings.Fields(text)[0], Tags: []string{"described", "topic-" + strings.TrimSuffix(title, ".go")}}
	if strings.HasSuffix(title, ".csv") {
		d.Columns = []ColumnNote{{Name: "T_degC", Intent: "water temperature"}}
	}
	return d, nil
}

func (f *fakeEnricher) described() []string {
	f.mu.Lock()
	defer f.mu.Unlock()
	return append([]string(nil), f.titles...)
}

// Files and documents get a summary and tags after each scan, within the
// day's budget and while no turn runs; generated, large and unreadable
// ones are skipped without a call; a hit carries its summary and tags,
// and a tag finds the file though its text doesn't say it.
func TestEnrichment(t *testing.T) {
	ctx := context.Background()
	files := newSource("files")
	files.set("cart.go", "package cart computes totals", t0)
	files.set("vendor/lib/x.go", "package lib", t0)
	files.set("api.pb.go", "// Code generated by protoc. DO NOT EDIT.\npackage api", t0)
	files.set("big.txt", strings.Repeat("y ", maxEnrichBytes), t0)
	files.put("locked.go", memItem{err: errors.New("denied"), mod: t0})
	chats := newSource("chats")
	chats.set("session-1", "a chat about totals", t0)
	var busy atomic.Bool
	enr := &fakeEnricher{}
	x, err := Open(t.TempDir(), []Source{files, chats}, nil, WithEnricher(enr, 10, busy.Load))
	require.NoError(t, err)
	t.Cleanup(func() { x.Close() })

	require.NoError(t, x.Scan(ctx))
	assert.Equal(t, []string{"cart.go"}, enr.described(), "only what's worth a call: not vendored, generated, large, unreadable files, nor chats")
	assert.Equal(t, 1, x.Status().Enriched)

	hits, err := x.Search(ctx, Query{Text: "topic-cart"})
	require.NoError(t, err)
	require.Len(t, hits, 1, "found by its tag")
	assert.Equal(t, "cart.go", hits[0].Ref)
	assert.Equal(t, "About cart.go: package", hits[0].Summary)
	assert.Equal(t, []string{"described", "topic-cart"}, hits[0].Tags)

	require.NoError(t, x.Scan(ctx))
	assert.Len(t, enr.described(), 1, "not described twice")

	busy.Store(true)
	files.set("cart.go", "package cart rounds totals", t0.Add(time.Second))
	require.NoError(t, x.Scan(ctx))
	assert.Len(t, enr.described(), 1, "paused while a turn runs")
	busy.Store(false)
	require.NoError(t, x.Scan(ctx))
	assert.Len(t, enr.described(), 2, "described again once changed")

	files.remove("cart.go")
	require.NoError(t, x.Scan(ctx))
	hits, err = x.Search(ctx, Query{Text: "topic-cart"})
	require.NoError(t, err)
	assert.Empty(t, hits, "its summary went with it")
}

// The day's budget holds across scans and restarts, and a new day starts
// it again; a model that fails is reported and tried again next scan.
func TestEnrichmentBudgetAndFailure(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	files := newSource("files")
	for _, f := range []string{"a.go", "b.go", "c.go"} {
		files.set(f, "package "+strings.TrimSuffix(f, ".go"), t0)
	}
	enr := &fakeEnricher{}
	x, err := Open(dir, []Source{files}, nil, WithEnricher(enr, 2, nil))
	require.NoError(t, err)
	require.NoError(t, x.Scan(ctx))
	assert.Len(t, enr.described(), 2, "the day's budget")
	require.NoError(t, x.Close())

	x, err = Open(dir, []Source{files}, nil, WithEnricher(enr, 2, nil))
	require.NoError(t, err)
	defer x.Close()
	require.NoError(t, x.Scan(ctx))
	assert.Len(t, enr.described(), 2, "still spent after a restart")

	_, err = x.db.Exec(`UPDATE meta SET value = '2000-01-01' WHERE key = 'enrich_day'`)
	require.NoError(t, err)
	enr.mu.Lock()
	enr.fail = errors.New("rate limited")
	enr.mu.Unlock()
	require.NoError(t, x.Scan(ctx), "a describing failure doesn't fail the scan")
	assert.Contains(t, x.Status().EnrichErr, "rate limited")

	enr.mu.Lock()
	enr.fail = nil
	enr.mu.Unlock()
	require.NoError(t, x.Scan(ctx))
	assert.Len(t, enr.described(), 3, "a new day: the last one described")
	assert.Empty(t, x.Status().EnrichErr)
	assert.Equal(t, 3, x.Status().Enriched)
}

// generated tells vendored and generated files by path or header.
func TestGenerated(t *testing.T) {
	for ref, want := range map[string]bool{
		"cmd/main.go":                 false,
		"vendor/x/y.go":               true,
		"web/node_modules/a/index.js": true,
		"proto/v1/x.pb.go":            true,
		"assets/app.min.js":           true,
		"go.sum":                      true,
		"docs/build.md":               false,
	} {
		assert.Equal(t, want, generated(ref, ""), ref)
	}
	assert.True(t, generated("x.go", "// Code generated by stringer; DO NOT EDIT.\npackage x"))
	assert.False(t, generated("x.go", "// Code generated by hand, edit freely\n"))
}

// A table is described however large it is (by its head), and what its
// columns hold is kept: searchable, and read back for the viewer.
func TestEnrichTable(t *testing.T) {
	ctx := context.Background()
	files := newSource("files")
	files.set("data/bottle.csv", "Sta_ID,T_degC\n"+strings.Repeat("054.0 056.0,10.5\n", 8000), t0)
	enr := &fakeEnricher{}
	x, err := Open(t.TempDir(), []Source{files}, nil, WithEnricher(enr, 10, nil))
	require.NoError(t, err)
	t.Cleanup(func() { x.Close() })
	require.NoError(t, x.Scan(ctx))
	assert.Equal(t, []string{"data/bottle.csv"}, enr.described(), "described past maxEnrichBytes")

	cols, err := x.Columns(ctx, "files", "data/bottle.csv")
	require.NoError(t, err)
	assert.Equal(t, []ColumnNote{{Name: "T_degC", Intent: "water temperature"}}, cols)
	none, err := x.Columns(ctx, "files", "missing.csv")
	require.NoError(t, err)
	assert.Nil(t, none)

	hits, err := x.Search(ctx, Query{Text: "water temperature"})
	require.NoError(t, err)
	require.Len(t, hits, 1, "found by what a column holds")
	assert.Equal(t, "data/bottle.csv", hits[0].Ref)
}
