load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "textutil",
    srcs = [
        "glob.go",
        "textutil.go",
    ],
    importpath = "github.com/retail-cortex/blitz/pkg/textutil",
    visibility = ["//visibility:public"],
)

go_test(
    name = "textutil_test",
    srcs = ["textutil_test.go"],
    embed = [":textutil"],
)
