#!/usr/bin/env bash
# Copyright 2026 Retail Cortex
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the Homebrew formula for a release (spec_parity_027 PAR-MOD-06),
# from its checksums.txt:
#
#   release/homebrew_formula.sh 0.1.0 checksums.txt > Formula/blitz.rb
#
# The release workflow pushes it to the retail-cortex/homebrew-tap
# repository when a release is published, so `brew install
# retail-cortex/tap/blitz` installs it.

set -euo pipefail

version="${1:?usage: homebrew_formula.sh <version> <checksums.txt>}"
sums="${2:?usage: homebrew_formula.sh <version> <checksums.txt>}"
version="${version#v}"
base="https://github.com/retail-cortex/blitz/releases/download/v$version"

sha() {
  local f="blitz_${version}_$1.tar.gz" s
  s="$(awk -v f="$f" '$2 == f { print $1 }' "$sums")"
  [ -n "$s" ] || { echo "homebrew_formula: $f isn't in $sums" >&2; exit 1; }
  echo "$s"
}

# Each assignment fails the script when an archive is missing.
darwin_arm64="$(sha darwin_arm64)"
darwin_amd64="$(sha darwin_amd64)"
linux_arm64="$(sha linux_arm64)"
linux_amd64="$(sha linux_amd64)"

cat <<RUBY
# Generated by release/homebrew_formula.sh for Blitz $version.
class Blitz < Formula
  desc "Coding agent for your terminal, with a desktop app and a local service"
  homepage "https://retail-cortex.github.io/blitz/"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/blitz_${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "$base/blitz_${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "$base/blitz_${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "$base/blitz_${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install "blitz", "blitzd"
    bin.install_symlink "blitz" => "blz"
    prefix.install "LICENSE", "NOTICE", "THIRD_PARTY_NOTICES"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blitz --version")
  end
end
RUBY
